spring:
  application:
    name: liquibase
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./demo-db-change
    driverClassName: org.h2.Driver
    username: sa
    password:
